env:
  node: true
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - "plugin:jest/recommended"
  - "plugin:fp/recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - fp
  - jest
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  fp/no-nil: 0
  fp/no-unused-expression: 0
  fp/no-throw: 0
  fp/no-mutating-methods:
    - error
    - allowedObjects: ["_"]
